version: '3.7'

services:

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    env_file: ./server/.env
    environment:
      - MONGODB_URL=mongodb+srv://bilal_anwarr:kunAguero10@cluster0.vavar.mongodb.net/bilal1?retryWrites=true&w=majority;
      - PORT=4000
    networks:
      - app-network

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
